language: r
r: release
sudo: required
warnings_are_errors: false

cache:
  packages: true

git: 
  depth: false

r_packages:
  - shiny
  - ggplot2
  - dplyr
  - jpeg
  - shinydashboard
  - httr
  - jsonlite
  - scales
  - forcats
  - cowplot
  - tidyverse
  - rsconnect
  - ggpubr
  - sqldf
  - RColorBrewer

script:
  - R -f deploy.R